### ISSUE TITLE
Certificate error when logging in to nintendo 

### ISSUE THREAD

**Issue by TomCasavant** [mathewthe2/splatnet-desktop#1]
I have no idea if you still manage this project at all, but I was looking into using the Animal Crossing API and was failing to get the session token's properly so I figured I'd just read the logs from this project and see if there's something wrong w/ my logic. After logging into nintendo, I get the screen "Logging into NSO" and then it freezes there. Checking the logs, here is the error I get:

```
RequestError: Error: certificate has expired
    at new RequestError (C:\Users\tfcas\splatnet-desktop\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\tfcas\splatnet-desktop\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\tfcas\splatnet-desktop\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\tfcas\splatnet-desktop\node_modules\request\request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (C:\Users\tfcas\splatnet-desktop\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8) {
  cause: Error: certificate has expired
      at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)
      at TLSSocket.emit (events.js:310:20)
      at TLSSocket._finishInit (_tls_wrap.js:927:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12) {
    code: 'CERT_HAS_EXPIRED'
  },
  error: Error: certificate has expired
      at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)
      at TLSSocket.emit (events.js:310:20)
      at TLSSocket._finishInit (_tls_wrap.js:927:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12) {
    code: 'CERT_HAS_EXPIRED'
  },
  options: {
    jar: RequestJar { _jar: [CookieJar] },
    method: 'POST',
    uri: 'https://elifessler.com/s2s/api/gen2',
    headers: { 'User-Agent': 'splatnetDesktop/1.0.0' },
    form: {
      naIdToken: 'REDACTED',
      timestamp: '1656192594'
    },
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}
```

**Comment by mathewthe2** [comment]
I haven't really updated this repo but I have a working server currently.

First thing is to update the user-agent header.

 headers: { 'User-Agent': 'splatnetDesktop/2.0.0' },

You can use name of your own app *myApp/1.0.0*.

The *elifessler* endpoint requires you to update your app's version every time the nso version updates.

**Comment by TomCasavant** [comment]
Thanks! I believe the header updating seems to have fixed it
